### ISSUE TITLE
Plug in doesn't launch : AttributeError: 'NoneType' object has no attribute 'parent'

### ISSUE THREAD

**Issue by ptycharly** [nextgis/QTiles#117]
Hi, I can't launch the plugin. I have the following error : 

`2022-10-14T09:41:48     WARNING    Traceback (most recent call last):
              File "/Users/gopubconseil/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qtiles/qtiles.py", line 97, in run
              d = qtilesdialog.QTilesDialog(self.iface)
              File "/Users/gopubconseil/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qtiles/qtilesdialog.py", line 91, in __init__
              self.manageGui()
              File "/Users/gopubconseil/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qtiles/qtilesdialog.py", line 131, in manageGui
              groupName = utils.getLayerGroup(layer[0])
              File "/Users/gopubconseil/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qtiles/qtiles_utils.py", line 57, in getLayerGroup
              return QgsProject.instance().layerTreeRoot().findLayer(layerId).parent().name()
             AttributeError: 'NoneType' object has no attribute 'parent'`

I use the latest version of QTile (1.7.1)
I Test it on Qgis LTR 3.22 an 3.26

Thank you!

**Comment by simgislab** [comment]
please update to latest version of the plugin and try again

**Comment by co00co** [comment]
Hello.
I'm using version 1.7.2 ,and got this error:
src/core/qgsmessagelog.cpp:29 : (logMessage) [24042ms] 2023-04-27T13:48:37 Error de Python[1] Traceback (most recent call last):
  File "/home/blah/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qtiles/qtiles.py", line 97, in run
    d = qtilesdialog.QTilesDialog(self.iface)
  File "/home/blah/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qtiles/qtilesdialog.py", line 91, in __init__
    self.manageGui()
  File "/home/blah/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qtiles/qtilesdialog.py", line 131, in manageGui
    groupName = utils.getLayerGroup(layer[0])
  File "/home/blah/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qtiles/qtiles_utils.py", line 57, in getLayerGroup
    return QgsProject.instance().layerTreeRoot().findLayer(layerId).parent().name()
AttributeError: 'NoneType' object has no attribute 'parent'

**Comment by boucur** [comment]
I receive the same error when attempting to launch the plugin for the first time in Q 3.28.1 (plugin version 1.7.2):

```
2023-05-24T12:51:29     WARNING    Traceback (most recent call last):
              File "C:\Users/blah2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qtiles\qtiles.py", line 97, in run
              d = qtilesdialog.QTilesDialog(self.iface)
              File "C:\Users/blah2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qtiles\qtilesdialog.py", line 91, in __init__
              self.manageGui()
              File "C:\Users/blah2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qtiles\qtilesdialog.py", line 131, in manageGui
              groupName = utils.getLayerGroup(layer[0])
              File "C:\Users/blah2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qtiles\qtiles_utils.py", line 57, in getLayerGroup
              return QgsProject.instance().layerTreeRoot().findLayer(layerId).parent().name()
             AttributeError: 'NoneType' object has no attribute 'parent'
             
             
```

**Comment by dezhin** [comment]
Can you share a screenshot of your layers panel before you're trying to launch the plugin? It seems something unusual there.
