### ISSUE TITLE
При запуске QGIS вот такая ошибка

### ISSUE THREAD

**Issue by drnextgis** [nextgis/QTiles#54]
Пробовал на `1.5.1` и `master` ветках.

```
Traceback (most recent call last):
  File "c:/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "c:/NEXTGI~1/apps/qgis/./python/plugins\QTiles\__init__.py", line 30, in classFactory
    from qtiles import QTilesPlugin
  File "c:/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "c:/NEXTGI~1/apps/qgis/./python/plugins\QTiles\qtiles.py", line 34, in 
    import qtilesdialog
  File "c:/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "c:/NEXTGI~1/apps/qgis/./python/plugins\QTiles\qtilesdialog.py", line 34, in 
    from ui.ui_qtilesdialogbase import Ui_Dialog
  File "c:/NEXTGI~1/apps/qgis/./python\qgis\utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named ui_qtilesdialogbase
```

**Comment by simgislab** [comment]
а ты как устанаваливаешь? git clone сделал? - этого мало

надо же еще `pyuic4 -o ui_qtilesdialogbase.py qtilesdialogbase.ui` и много еще чего

**Comment by drnextgis** [comment]
Спасибо, вот это сделал и заработало:

```
pyuic4 -o ui_qtilesdialogbase.py qtilesdialogbase.ui
pyuic4 -o ui_aboutdialogbase.py aboutdialogbase.ui
```
